const test=require('node:test'),assert=require('node:assert/strict');
const {projectTrackFilter,projectRealm}=require('../lib/publicProjects'),r=require('../resolvers'),W=require('../models/ReleaseWorld'),T=require('../models/ReleaseTrack'),C=require('../models/NexusEditorialConfig');
test('Contextual tracklist uses project ownership, listed access and sequence, never child Canon',async()=>{
 const old=[W.find,T.find,C.findOne];try{C.findOne=async()=>({selectedWorldIds:['w']});W.find=q=>({sort:async()=>{assert.equal(q.publicCanon,true);assert.equal(q.visibility,'public');assert.deepEqual(q._id,{$in:['w']});return [{_id:'w',ownerId:'a'}];}});T.find=q=>({sort:async order=>{assert.equal(q.ownerId,'a');assert.equal(q.releaseWorldId,'w');assert.deepEqual(q.catalogTreatment,{$nin:['vault','test']});assert.deepEqual(q.$or[0],{visibility:{$in:['public','listed']}});assert.equal(q.publicCanon,undefined);assert.equal(order.trackNumber,1);return [{id:'listed',visibility:'listed',publicCanon:false,realmId:101,isFocusTrack:true}];}});const result=await r.Query.publicProjects(null,{selectedOnly:true});assert.equal(result[0].tracks[0].publicCanon,false);assert.equal(result[0].realmId,101);}finally{[W.find,T.find,C.findOne]=old;}
});
test('Project Realm derives from canonical focus or unanimous child context without changing choices',()=>{assert.equal(projectRealm([{realmId:202,isFocusTrack:true},{realmId:303}]),202);assert.equal(projectRealm([{realmId:202},{realmId:303}]),null);assert.equal(projectRealm([]),null);assert.equal(projectTrackFilter({_id:'w',ownerId:'a'}).status.$ne,'archived');});
test('Creator cannot self-select a Nexus project; editorial selection requires public Canon',async()=>{await assert.rejects(r.Mutation.setNexusProjectSelection(null,{worldId:'w',selected:true},{user:{id:'a',role:'creator',creatorStatus:'active'}}),/editorial|permission|Owner|access/i);const old=W.findOne;try{W.findOne=async()=>null;await assert.rejects(r.Mutation.setNexusProjectSelection(null,{worldId:'w',selected:true},{user:{id:'admin',role:'owner'}}),/public Canon/);}finally{W.findOne=old;}});
test('Project GraphQL document matches schema',()=>{const {makeExecutableSchema}=require('@graphql-tools/schema'),{parse,validate}=require('graphql'),fs=require('node:fs');const schema=makeExecutableSchema({typeDefs:require('../schemas'),resolvers:r});const source=fs.readFileSync('../frontend/src/graphql/publicProjects.ts','utf8');assert.deepEqual(validate(schema,parse(source.match(/gql`([\s\S]*?)`/)[1])).map(e=>e.message),[]);});
test('Editorial project selection updates references only, never project or child content',async()=>{
 const old=[W.findOne,C.findOne,C.findOneAndUpdate];try{W.findOne=async()=>({_id:'world',publicCanon:true,visibility:'public'});C.findOne=async()=>({_id:'config',selectedWorldIds:[]});C.findOneAndUpdate=async(q,u)=>{assert.deepEqual(q,{_id:'config'});assert.deepEqual(u,{$addToSet:{selectedWorldIds:'world'},$set:{updatedBy:'editor'}});return {selectedWorldIds:['world']};};const result=await r.Mutation.setNexusProjectSelection(null,{worldId:'world',selected:true},{user:{id:'editor',role:'owner'}});assert.deepEqual(result.selectedWorldIds,['world']);}finally{[W.findOne,C.findOne,C.findOneAndUpdate]=old;}
});
