const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(name){const m={exports:{}};const code=ts.transpileModule(fs.readFileSync(`src/lib/${name}.ts`,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;vm.runInNewContext(`(function(require,module,exports){${code}})`)(n=>load(n.replace('./','')),m,m.exports);return m.exports;}
const {analyzeCatalog,signalQuality}=load('catalogIntelligence');
const {catalogCleanupAction}=load('catalogCleanupActions');
const a=['defiant','driving','dark','breakthrough'],b=['romantic','floating','dreamy','memory'];
const track=(id,signals=[],extra={})=>({id,ownerId:'owner',creativeSignals:signals,realmId:101,...extra});
const catalog=[...['a','b','c'].map(id=>track(id,a)),...['d','e','f'].map(id=>track(id,b)),track('bridge',[...a,...b]),track('orbit',['peaceful','still','awareness']),track('sparse',['dark'])];
test('Realm alone and sparse evidence cannot generate clusters or outliers',()=>{const r=analyzeCatalog([track('a'),track('b',['dark'])],'owner');assert.equal(r.edges.length,0);assert.equal(r.clusters.length,0);assert.equal(r.ownOrbits.length,0);assert.equal(r.needsSignals.length,2);});
test('Complete-link cores, bridges, own orbits and sparse tracks remain distinct',()=>{const r=analyzeCatalog(catalog,'owner');assert.equal(r.hypotheses.length,2);assert.ok(r.bridges.some(b=>b.trackId==='bridge'));assert.equal(r.ownOrbits.join(','),'orbit');assert.equal(r.needsSignals.join(','),'sparse');for(const c of r.clusters)for(const left of c.trackIds)for(const right of c.trackIds)if(left!==right)assert.ok(r.edges.some(e=>[e.a,e.b].includes(left)&&[e.a,e.b].includes(right)));});
test('Analysis is read-only, title-independent and input-order deterministic',()=>{const before=JSON.stringify(catalog),first=analyzeCatalog(catalog,'owner');assert.equal(JSON.stringify(analyzeCatalog([...catalog].reverse(),'owner')),JSON.stringify(first));assert.equal(JSON.stringify(catalog),before);assert.equal(JSON.stringify(analyzeCatalog(catalog.map(t=>({...t,title:'Different'})),'owner')),JSON.stringify(first));});
test('Owner isolation and lifecycle exclusions are fail-closed',()=>{const extra=[track('foreign',a,{ownerId:'other'}),track('test',a,{catalogTreatment:'test'}),track('vault',a,{catalogTreatment:'vault'}),track('archived',a,{status:'archived'})];assert.equal(analyzeCatalog([...catalog,...extra],'owner').edges.length,analyzeCatalog(catalog,'owner').edges.length);assert.equal(analyzeCatalog(extra,'owner').total,0);assert.equal(analyzeCatalog(catalog,'').total,0);});
test('Explanations use actual shared signals; pairs are not project hypotheses',()=>{const r=analyzeCatalog([track('a',a),track('b',a)],'owner');assert.equal(r.hypotheses.length,0);assert.equal(r.edges[0].shared.length,4);assert.ok(r.clusters[0].why.includes('defiant'));});
test('Signal health measures explicit usage and retains rare vocabulary',()=>{const q=signalQuality(catalog,'owner');assert.equal(q.length,26);assert.equal(q.find(q=>q.signal==='dark').count,5);assert.equal(q.find(q=>q.signal==='hazy').count,0);assert.equal(q.find(q=>q.signal==='hazy').finding,'Insufficient usage data');assert.equal(q.find(q=>q.signal==='defiant').cooccurrence.find(p=>p.signal==='driving').count,4);});
test('Cleanup payloads preserve files, ownership, Realm and project links',()=>{assert.equal(JSON.stringify(catalogCleanupAction('test').input),'{"catalogTreatment":"test"}');assert.equal(JSON.stringify(catalogCleanupAction('archive').input),'{"archive":true}');assert.match(catalogCleanupAction('test').confirmation,/Files and project membership stay intact/);});
test('Cleanup requires confirmation and never writes on render or cancellation',async()=>{
 let confirms=false,calls=[];const m={exports:{}};
 const code=ts.transpileModule(fs.readFileSync('src/components/creator/CatalogCleanupActions.tsx','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText;
 vm.runInNewContext(`(function(require,module,exports){${code}})`,{window:{confirm:()=>confirms}})(n=>n==='react'?{useState:v=>[v,()=>{}]}:n.includes('catalogCleanupActions')?{catalogCleanupAction}:require(n),m,m.exports);
 const tree=m.exports.default({status:'demo',onSave:async input=>calls.push(input)});
 assert.equal(calls.length,0);const buttons=tree.props.children.filter(c=>c?.type==='button');buttons[0].props.onClick();await Promise.resolve();assert.equal(calls.length,0);
 confirms=true;buttons[0].props.onClick();await Promise.resolve();assert.equal(calls[0].catalogTreatment,'test');buttons[1].props.onClick();await Promise.resolve();assert.equal(calls[1].archive,true);
});
